/**
 * Utility to communicate with the xAI Grok API for generating blog posts.
 */

/**
 * Generates a blog post outline or full article using Grok API.
 * @param {string} prompt - The blog topic or user prompt.
 * @returns {Promise<Object>} The title, summary, and content generated by Grok.
 */
async function generateBlogWithGrok(prompt) {
  const apiKey = process.env.GROQ_API_KEY || process.env.XAI_API_KEY;
  if (!apiKey) {
    throw new Error('Groq API Key is missing in environment variables.');
  }

  const systemMessage = `
You are an expert technical blog writer and SEO specialist for SSSAM Academy.
Your task is to write high-quality, engaging, and search-engine-optimized educational content.
Respond ONLY with a JSON object containing the fields: "title", "summary", and "content" (in HTML format).
Do not wrap your output in markdown code blocks like \`\`\`json. Just output the raw JSON.

JSON Structure:
{
  "title": "SEO-friendly Title",
  "summary": "Short 2-3 sentence meta description for search engines",
  "content": "<p>Intriguing introduction...</p><h2>Key Concepts</h2><p>Detailed analysis...</p>"
}
`;

  try {
    const response = await fetch('https://api.groq.com/openai/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model: 'llama-3.3-70b-versatile', // Fast Groq Llama 3.3 model
        messages: [
          { role: 'system', content: systemMessage },
          { role: 'user', content: `Write a blog post about: ${prompt}` },
        ],
        temperature: 0.7,
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Groq API returned error: ${response.status} - ${errorText}`);
    }

    const data = await response.json();
    const resultText = data.choices[0].message.content.trim();

    // Parse the JSON output from Grok
    let cleanJson = resultText;
    // Strip markdown JSON wrappers if Grok accidentally outputted them
    if (cleanJson.startsWith('```json')) {
      cleanJson = cleanJson.substring(7);
    }
    if (cleanJson.endsWith('```')) {
      cleanJson = cleanJson.substring(0, cleanJson.length - 3);
    }

    return JSON.parse(cleanJson.trim());
  } catch (err) {
    console.error('Grok Generation Error:', err.message);
    throw err;
  }
}

module.exports = {
  generateBlogWithGrok,
};
