/**
 * Utility to communicate with the xAI / Groq API for generating blog posts and SEO tags.
 */

/**
 * Generates a blog post outline or full article using Grok API.
 * @param {string} prompt - The blog topic or user prompt.
 * @returns {Promise<Object>} The title, summary, content, and tags generated by Grok.
 */
async function generateBlogWithGrok(prompt) {
  const apiKey = process.env.GROQ_API_KEY || process.env.XAI_API_KEY;
  if (!apiKey) {
    throw new Error('Groq API Key is missing in environment variables.');
  }

  const systemMessage = `
You are an expert technical blog writer and SEO specialist for SSSAM Academy.
Your task is to write high-quality, engaging, and search-engine-optimized educational content.
Respond ONLY with a JSON object containing the fields: "title", "summary", "content" (in HTML format), and "tags" (an array of 5-7 lowercase relevant SEO tags).
Do not wrap your output in markdown code blocks like \`\`\`json. Just output the raw JSON.

Formatting Rules:
1. "title" MUST be formatted in proper Title Case with correct capitalization (e.g., "Emerging Tech Landscapes: Top IT Trends in 2026"). Technical acronyms (IT, AI, ML, SEO, JS, AWS, SQL, MERN) MUST be in UPPERCASE.
2. "content" MUST use clean, well-spaced HTML with <h2>, <h3>, <p>, <ul>, <li>, and <strong> tags.
3. "summary" MUST be a crisp 2-3 sentence meta description.

JSON Structure:
{
  "title": "Title Case SEO-friendly Title",
  "summary": "Short 2-3 sentence meta description for search engines",
  "content": "<p>Intriguing introduction...</p><h2>Key Concepts</h2><p>Detailed analysis...</p>",
  "tags": ["tag1", "tag2", "tag3", "tag4", "tag5"]
}
`;

  try {
    const response = await fetch('https://api.groq.com/openai/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model: 'llama-3.3-70b-versatile', // Fast Groq Llama 3.3 model
        messages: [
          { role: 'system', content: systemMessage },
          { role: 'user', content: `Write a unique and fresh blog post about: "${prompt}". Seed/Variant token: ${Math.random().toString(36).substring(7)}` },
        ],
        temperature: 0.95,
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Groq API returned error: ${response.status} - ${errorText}`);
    }

    const data = await response.json();
    const resultText = data.choices[0].message.content.trim();

    // Parse the JSON output from Grok
    let cleanJson = resultText;
    
    // Strip markdown JSON wrappers if Grok accidentally outputted them
    if (cleanJson.startsWith('```json')) {
      cleanJson = cleanJson.replace(/^```json\s*/i, '');
    } else if (cleanJson.startsWith('```')) {
      cleanJson = cleanJson.replace(/^```\s*/, '');
    }
    if (cleanJson.endsWith('```')) {
      cleanJson = cleanJson.replace(/```$/, '');
    }
    
    cleanJson = cleanJson.trim();

    try {
      // Fix escaping backslash issues commonly produced by AI APIs
      const scrubbed = cleanJson.replace(/\\(?!["\\\/bfnrtu])/g, "\\\\");
      const parsed = JSON.parse(scrubbed);
      if (!parsed.tags || !Array.isArray(parsed.tags)) {
        parsed.tags = ["technology", "coding", "tutorial", "career", "sssam academy"];
      }
      return parsed;
    } catch (parseErr) {
      console.warn("JSON parsing failed, falling back to regex parser", parseErr.message);
      
      // Regex parsing fallback if JSON is still slightly malformed
      const titleMatch = cleanJson.match(/"title"\s*:\s*"([^"]+)"/);
      const summaryMatch = cleanJson.match(/"summary"\s*:\s*"([^"]+)"/);
      let content = cleanJson;
      
      // Clean content from JSON wrapping if possible
      const contentMatch = cleanJson.match(/"content"\s*:\s*"([\s\S]+)"\s*\}?$/);
      if (contentMatch) {
        content = contentMatch[1];
      }

      return {
        title: titleMatch ? titleMatch[1] : prompt,
        summary: summaryMatch ? summaryMatch[1] : "AI Generated Blog content.",
        content: content || resultText,
        tags: ["technology", "coding", "tutorial", "sssam academy"]
      };
    }
  } catch (err) {
    console.error('Grok Generation Error:', err.message);
    const cleanTopic = prompt.replace(/^Write a unique and fresh blog post about:\s*"/i, '').replace(/".*$/, '').trim();
    return {
      title: `${cleanTopic.charAt(0).toUpperCase() + cleanTopic.slice(1)} - Guide & Overview`,
      summary: `A comprehensive overview and practical guide on ${cleanTopic} from SSSAM Academy.`,
      content: `<h2>Introduction to ${cleanTopic}</h2><p>Learning ${cleanTopic} provides essential industry skills and knowledge. In this guide, we cover core concepts, real-world applications, and best practices.</p><h2>Key Concepts</h2><ul><li>Fundamental Principles &amp; Syntaxes</li><li>Practical Application &amp; Workflows</li><li>Industry Best Practices for Career Growth</li></ul><p>Mastering these topics will help build a strong technical foundation.</p>`,
      tags: ["technology", "coding", "sssam academy", "tutorial"]
    };
  }
}

/**
 * Generates SEO tags using Grok API.
 * @param {string} prompt - The blog title or content summary.
 * @returns {Promise<Object>} An object containing the generated tags string.
 */
async function generateTagsWithGrok(prompt) {
  const apiKey = process.env.GROQ_API_KEY || process.env.XAI_API_KEY;
  if (!apiKey) {
    throw new Error('Groq API Key is missing in environment variables.');
  }

  try {
    const response = await fetch('https://api.groq.com/openai/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model: 'llama-3.3-70b-versatile',
        messages: [
          {
            role: 'system',
            content: 'You are an SEO tag generator. Given a blog topic, title, or content, generate 5-8 highly relevant, concise, lowercase SEO tags. Return ONLY a JSON object with a "tags" array, for example: {"tags": ["python", "coding", "jobs", "tutorial", "development"]}. Do not include markdown code block wrappers.'
          },
          { role: 'user', content: prompt },
        ],
        temperature: 0.7,
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Groq API returned error: ${response.status} - ${errorText}`);
    }

    const data = await response.json();
    const resultText = data.choices[0].message.content.trim();
    let cleanJson = resultText.replace(/^```json\s*/i, '').replace(/^```\s*/, '').replace(/```$/, '').trim();

    try {
      const parsed = JSON.parse(cleanJson);
      if (Array.isArray(parsed.tags)) {
        return { tags: parsed.tags.join(', ') };
      }
      if (typeof parsed.tags === 'string') {
        return { tags: parsed.tags };
      }
    } catch (_) {}

    return { tags: resultText.replace(/[*#`"']/g, '').replace(/\n/g, ', ') };
  } catch (err) {
    console.error('Grok Tags Generation Error:', err.message);
    return { tags: 'technology, coding, tutorial, sssam academy, career' };
  }
}

module.exports = {
  generateBlogWithGrok,
  generateTagsWithGrok,
};
